import './logout';
import './login';
import './search-model-form';
import './test-hbs';
import './register';
import './menuBtn';
import './card-favorites';
import './pagination';
import './searchApiServis';
