import 'regenerator-runtime/runtime';
import './sass/main.scss';
import './js/header/header-main';
import './js/start-page/start-page';
import './js/header/pagination';
import './js/main/catigoriesApi';
import './js/main/add-modal-logic/main-add-modal';
import './js/my-cabinet/main-myCabinet';
import './js/header/render-categories-taras';
// import './js/pagination/main';
import './js/routes/router';
import './js/routes/rout-main';
import './js/routes/update-page';
import './js/routes/search';
import './js/routes/category';
import './js/routes/main-pages';
import './js/main/edit-modal.logic.js/open-edit-modal';
